### ISSUE TITLE
http或ws监听/help命令会被console捕获而不是被onebot处理[BUG]

### ISSUE THREAD

**Issue by LittleNightmare** [yyuueexxiinngg/onebot-kotlin#110]
私聊或群里中发送/help，会被console处理，而不是onebot-kotlin。似乎[权限](https://github.com/mamoe/mirai-console/blob/master/docs/Permissions.md)是造成的？

```
2020-11-21 12:02:16 V/Bot xxxxxxxxxxxx: AAAAA(aaaaaaaaaaaaa) -> [mirai:source:19589,2139671256]/help
2020-11-21 12:02:18 V/Bot xxxxxxxxxxxx: Friend(aaaaaaaaaaaaa) <- 权限不足
```

#### 复现

1. 私聊，或群聊bot
2. 发送/help

#### 版本
onebot-` kotlin`- ` 0.3.0`

**Comment by yyuueexxiinngg** [comment]
`/help`命令为`mirai-console`的内建命令, `onebot-kotlin-0.3.0`基于`mirai-console-1.0-RC-1`, 此版console内置聊天环境触发命令功能导致console本身的命令被触发, 未广播消息事件

参考https://github.com/mamoe/mirai-console/issues/161

在`mirai-console 1.0`正式版后, 移除了聊天环境触发命令的功能, `onebot-kotlin-0.3.1`基于此版本, 尚未Release, 可在最新[Action](https://github.com/yyuueexxiinngg/onebot-kotlin/actions)中提前下载使用
