### ISSUE TITLE
[Feature] 闪照处理 以及图片后缀名的处理

### ISSUE THREAD

**Issue by GOGOsu** [yyuueexxiinngg/onebot-kotlin#114]
收到的闪照（mirai 消息格式 [mirai:flash:{UUID-HERE}.mirai]）提交 HTTP POST 时 message 部分显示此处消息的转义尚未被插件支持

普通图片在 get_image 获取之后希望能直接在文件后面加上副档名，方便使用

**Comment by yyuueexxiinngg** [comment]
已添加闪照支持, `get_image`没有后缀因为返回的是图片的路径, 下载时不知道图片的具体格式所以不含后缀名
