### ISSUE TITLE
[BUG] `onebot.account` 和 `onebot.password` 无法作为环境变量的标识符

### ISSUE THREAD

**Issue by shniubobo** [yyuueexxiinngg/onebot-kotlin#117]
```console
$ sh -c "export onebot.account=1"
sh: 1: export: onebot.account: bad variable name

$ bash -c "export onebot.account=1"
bash: line 0: export: `onebot.account=1': not a valid identifier

$ zsh -c "export onebot.account=1"
zsh:export:1: not valid in this context: onebot.account
```

#### 复现

见上方控制台报错。

#### 版本

与版本无关，点不能出现在环境变量的名字里。

如果一定需要 `.` 的话也不是不可以，但不能用 `export`。一个可用的 workaround：

```console
$ env onebot.account=1 python3 -c "import os; print(os.environ['onebot.account'])"
1
```

（这里用 `python3` 只是为了演示这个环境变量被成功设置了）

**Comment by yyuueexxiinngg** [comment]
这个是当时为了和`mirai-console 0.5.2`的property风格一致这么写的, 将在下个Release改为

- `ONEBOT_ACCOUNT`
- `ONEBOT_PASSWORD`
- `ONEBOT_BACKEND`

另外对于Windows上的PowerShell用户, 目前要设置带点的环境变量要这样 `${env:onebot.account} = "123456"`
