### ISSUE TITLE
[Question] CQ是否还可以使用

### ISSUE THREAD

**Issue by sulinwork** [yyuueexxiinngg/onebot-kotlin#118]
http://localhost:5700/send_group_msg?group_id=642429422&auto_escape=true&message=[CQ:at,qq=1527938786]

我这样请求发送 收到是
![image](https://user-images.githubusercontent.com/42666595/101155639-5f63c100-3662-11eb-8585-cd2009b19dcd.png)

不知道是什么问题  其他的CQ也使用不了

**Comment by yyuueexxiinngg** [comment]
https://github.com/howmanybots/onebot/blob/master/legacy/API.md#send_group_msg-%E5%8F%91%E9%80%81%E7%BE%A4%E6%B6%88%E6%81%AF


`auto_escape` | boolean | `false` | 消息内容是否作为纯文本发送（即不解析 CQ 码），只在 `message` 字段是字符串时有效
-- | -- | -- | --
