### ISSUE TITLE
[BUG] 连续重连进程卡死

### ISSUE THREAD

**Issue by StarHeartHunt** [yyuueexxiinngg/onebot-kotlin#128]
在正常登录一段时间后，连接断开且提示no server available，开始无限重试最后卡死进程

![IMG_20210121_175934](https://user-images.githubusercontent.com/14922941/105335584-2df38480-5c13-11eb-9571-12973b57dbe6.jpg)

#### 复现

1. 正常登录、配置
2. 放置一段时间
3. bot断开连接，出现上图所示的日志

#### 版本
onebot-`Kotlin`- `0.3.4`

 390eccc

**Comment by StarHeartHunt** [comment]
好像是mirai的问题，现在0.3.3也出现了。
mirai#708

**Comment by StarHeartHunt** [comment]
mirai昨天发了2.1.0，似乎修了无限重连卡死的问题。

**Comment by yyuueexxiinngg** [comment]
mirai的问题, mirai`2.1.0`以及`2.1.1`都有尝试修复断线重连的问题, 可去官方repo跟进
