### ISSUE TITLE
[BUG]断线重连，CPU占满并且堆溢出

### ISSUE THREAD

**Issue by OhnkytaBlabdey** [yyuueexxiinngg/onebot-kotlin#130]
服务器1核2G，1M带宽，最近经常突然地未响应断线，日志显示大量断线重连，以及堆溢出
![image](https://user-images.githubusercontent.com/26178665/105626032-68099400-5e68-11eb-8cf0-07aa2c054f5f.png)

CPU满了进不去控制台，重启之后日志主要就是这几句在重复
```

W/Net xx: Network force offline: returnCode = -10008
V/Net xx: Send: MessageSvc.PbGetMsg
I/Net xx: Syncing friend message history...

```

#### 复现

没有找到出现的原因，但是22日和24日出现过2次了

#### 版本
onebot-` kotlin`- ` 0.3.3` 

mirai-core-` `   

mirai-console-` `

**Comment by yyuueexxiinngg** [comment]
在mirai `2.1.0`中修复
https://github.com/mamoe/mirai/issues/879

**Comment by OhnkytaBlabdey** [comment]
请问插件支持新版的mirai吗 我需要换成2.1.0版本？
