### ISSUE TITLE
关于message_id[Question]

### ISSUE THREAD

**Issue by KagamiMiro** [yyuueexxiinngg/onebot-kotlin#134]
收到的message_id感觉像编码错了一样，正负号乱蹦，不知道是mirai的问题还是onebot的问题((下图是按时间倒序排列的
![image](https://user-images.githubusercontent.com/44522430/106293664-3ab64f00-6289-11eb-8e52-4518bf4655ea.png)

**Comment by yyuueexxiinngg** [comment]
正常行为, mirai不像酷Q有自己维护的`message_id`, 插件也没用维护, 仅用CRC对消息来源简单进行了hash作为`message_id`, 所以会乱跳
