### ISSUE TITLE
[Question]为啥bot运行久了会抛出no server available异常？

### ISSUE THREAD

**Issue by mgsky1** [yyuueexxiinngg/onebot-kotlin#142]
异常信息如下，如果需要我提供更多信息，我会及时补充～
- onebot-kotlin版本：`onebot-kotlin-0.3.4-all`
- Java版本：1.8.0_102
- 服务器系统：Windows Server 2012 R2 Datacenter
- 运行的组件: [FG](https://github.com/mgsky1/FG)，基于Onebot v10
<img width="587" alt="QQ20210629-165238@2x" src="https://user-images.githubusercontent.com/23556693/123975977-5c5e6280-d9f0-11eb-9f57-bfa2b4aa404b.png">

**Comment by yyuueexxiinngg** [comment]
#131 #130 #128 
`0.3.4 Release`中内建的`mirai`版本有点老了, 用自动构建的试试
https://github.com/yyuueexxiinngg/onebot-kotlin/actions/runs/860637836

**Comment by mgsky1** [comment]
好的，我试一段时间看看～这种问题一般是运行一段时间后出现

> #131 #130 #128
> `0.3.4 Release`中内建的`mirai`版本有点老了, 用自动构建的试试
> https://github.com/yyuueexxiinngg/onebot-kotlin/actions/runs/860637836
