### ISSUE TITLE
Embedded0.2.1私聊nonebot命令重复触发Event: MessageSvcPbGetMsg.Response，群聊则不会

### ISSUE THREAD

**Issue by mahosho** [yyuueexxiinngg/onebot-kotlin#43]
日志如下：
[INFO] [NETWORK] Send: MessageSvc.PbGetMsg
[INFO] [NETWORK] Send: MessageSvc.PbSendMsg
[INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
[INFO] [BOT xxxxxx] Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iterable>)
[INFO] [NETWORK] Send: MessageSvc.PbGetMsg
[INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
[INFO] [BOT xxxxxx] Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iterable>)
[INFO] [NETWORK] Send: MessageSvc.PbGetMsg
[INFO] [NETWORK] Recv: MessageSvcPbSendMsg.Response.SUCCESS
[INFO] [BOT xxxxxx] Friend(470131799) <- 咕噜灵波~
[INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
[INFO] [BOT xxxxxx] Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iterable>)
[INFO] [NETWORK] Send: MessageSvc.PbGetMsg
[INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
[INFO] [BOT xxxxxx] Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iterable>)
[INFO] [NETWORK] Send: MessageSvc.PbGetMsg
[INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
[INFO] [BOT xxxxxx] Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iterable>)
[INFO] [NETWORK] Send: MessageSvc.PbGetMsg
[INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
[INFO] [BOT xxxxxx] Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iterable>)
[INFO] [NETWORK] Send: MessageSvc.PbGetMsg
[INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
[INFO] [BOT xxxxxx] Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iterable>)
[INFO] [NETWORK] Send: MessageSvc.PbGetMsg
[INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
[INFO] [BOT xxxxxx] Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iterable>)
[INFO] [NETWORK] Send: MessageSvc.PbGetMsg
[INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
[INFO] [BOT xxxxxx] Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iterable>)
[INFO] [NETWORK] Send: MessageSvc.PbGetMsg
[INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
[INFO] [BOT xxxxxx] Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iterable>)
[INFO] [NETWORK] Send: MessageSvc.PbGetMsg
[INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
[INFO] [BOT xxxxxx] Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iterable>)
[INFO] [NETWORK] Send: MessageSvc.PbGetMsg
[INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg

**Comment by mahosho** [comment]
补充：重启后正常

**Comment by yyuueexxiinngg** [comment]
https://github.com/mamoe/mirai/issues/249
