### ISSUE TITLE
[BUG]WS Reverse重连有几率出现WS会话未清除导致重连失败

### ISSUE THREAD

**Issue by yyuueexxiinngg** [yyuueexxiinngg/onebot-kotlin#81]
相关Issue: https://github.com/yyuueexxiinngg/cqhttp-mirai/issues/74

```
15:05:13 [WARNING] [CQHTTPMirai] WS Reverse事件发送失败, 连接已被关闭, 尝试重连中 127.0.0.1:8080-Client-Universal
 15:05:13 [DEBUG] [CQHTTPMirai] 127.0.0.1:8080-Client-Universal 开始启动
 15:05:13 [WARNING] [CQHTTPMirai] Websocket session alredy exist, 127.0.0.1:8080-Client-Universal
```

#### 复现

Websocket 反向客户端重连时概率出现

#### 版本
cqhttp-mirai- `0..2.3 ` 

Commit: https://github.com/yyuueexxiinngg/cqhttp-mirai/commit/8621e256f8b29426a9188390caba8b82db5022fc

mirai-core-`1.2.2 `   

mirai-console-` 0.5.2`

**Comment by yimo0908** [comment]
我也复现了这个bug
版本信息: `onebot-kotlin-0.3.2-all`
```
2020-11-24 10:01:37 W/OneBot: WS Reverse事件发送失败, 连接已被关闭, 尝试重连中 xn--v9x.net:80-Client-Universal
2020-11-24 10:01:37 W/OneBot: Websocket session already exist, xn--v9x.net:80-Client-Universal
```

**Comment by LittleNightmare** [comment]
随着时间的增加，概率会变成必然

**Comment by yyuueexxiinngg** [comment]
刚Push了一个修复尝试, 请在Action中下载测试, 谢谢

**Comment by LittleNightmare** [comment]
> 刚Push了一个修复尝试, 请在Action中下载测试, 谢谢

已经开始测试了，挂一会看看吧
